name: shinycms
services:
  app_shinycms:  # Add web service
    container_name: app_shinycms
    networks:
      - shinycms_network
    build: 
      context: .
      dockerfile: docker/Dockerfile
      args:
      # KAI 20250325: Moving build environment variables to docker compose
        APP_DIR: /opt/shinycms
        APP_USER: shinycms
        APP_PORT: 6174
        APP_NAME: ShinyCMS
        SHINYCMS_CONFIG: /opt/shinycms/config/shinycms.conf
    image: app_shinycms:latest
    ports:
      - "6174:6174"  # ShinyCMS default port; Catalyst default is 5000
    environment:
# WBRASWELL 20250311: moved all environmental variables from Dockerfile to docker-compose.yml
      - APP_NAME=ShinyCMS
      - APP_PORT=6174
      - APP_USER=shinycms
      - APP_DIR=/opt/shinycms
      - SHINYCMS_CONFIG=/opt/shinycms/config/shinycms.conf
# NEED UPGRADE, WBRASWELL 20250311: move from 1 (shiny + db) to 2 docker containers (shiny & db)
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - DB_PORT=${DB_PORT}
#      - DB_HOST=${DB_HOST}
    volumes:
      - ".:/app"
# NEED UPGRADE, WBRASWELL 20250311: move from 1 (shiny + db) to 2 docker containers (shiny & db)
#    depends_on:
#      db_shinycms:
#        condition: service_healthy 
#  db_shinycms:  # Add PostgreSQL service
#    container_name: db_shinycms
#    networks:
#      - shinycms_network
#    build:
#      context: .
#      dockerfile: docker/Dockerfile-psql
#    image: db_shinycms:latest
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U shinycms_dbuser -d shinycms"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#    volumes:
#      -  db_shinycms_data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432" # For Development only
volumes:
#  db_shinycms_data:
#    name: db_shinycms_data
  app_shinycms_data:
    name: app_shinycms_data
networks:
  shinycms_network:
    name: shinycms_network
