FROM postgres:17.2

# OS Setup
RUN apt update
RUN apt-get install -y sudo

# Postgresql extension
RUN apt-get install -y postgresql-contrib
RUN apt-get install -y postgis postgresql-17-postgis-3
RUN apt-get install -y postgresql-17-pgvector
RUN apt-get install -y postgresql-17-cron

# Clean up
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Make postgres user sudoer (maybe don't want this in production)
RUN echo "postgres        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
RUN sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers

RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample

# Add the database initialization script
ADD psql/001-conf.sh /docker-entrypoint-initdb.d
ADD psql/002-init.sql /docker-entrypoint-initdb.d
